In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/krishnaik06/Hyperparameter-Optimization/master/Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.Gender[df.Gender=='Male']=1
df.Gender[df.Gender=='Female']=0


/home/gaurav/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/gaurav/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [5]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography Gender  Age  Tenure  \
0          1    15634602  Hargrave          619    France      0   42       2   
1          2    15647311      Hill          608     Spain      0   41       1   
2          3    15619304      Onio          502    France      0   42       8   
3          4    15701354      Boni          699    France      0   39       1   
4          5    15737888  Mitchell          850     Spain      0   43       2   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
2  159660.80              3          1               0        113931.57   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   

   Exited  
0       1  
1       0  
2       1  
3       0  
4       0

In [6]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [8]:
x=df.iloc[:,3:12].values

In [9]:
x

array([[619, 'France', 0, ..., 1, 1, 1],
       [608, 'Spain', 0, ..., 1, 0, 1],
       [502, 'France', 0, ..., 3, 1, 0],
       ...,
       [709, 'France', 0, ..., 1, 0, 1],
       [772, 'Germany', 1, ..., 2, 1, 0],
       [792, 'France', 0, ..., 1, 1, 0]], dtype=object)

In [10]:
y=df.iloc[:,13].values

In [11]:
y.shape

(10000,)

In [12]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [13]:
le_geo=LabelEncoder()

In [14]:
x[:,1]=le_geo.fit_transform(x[:,1])

In [15]:
#le_gender=LabelEncoder()

In [16]:
#x[:,2]=le_gender.fit_transform(x[:,2])

In [17]:
ss=StandardScaler()

In [18]:
x=ss.fit_transform(x)
x

/home/gaurav/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/gaurav/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.32622142, -0.90188624, -1.09598752, ..., -0.91158349,
         0.64609167,  0.97024255],
       [-0.44003595,  1.51506738, -1.09598752, ..., -0.91158349,
        -1.54776799,  0.97024255],
       [-1.53679418, -0.90188624, -1.09598752, ...,  2.52705662,
         0.64609167, -1.03067011],
       ...,
       [ 0.60498839, -0.90188624, -1.09598752, ..., -0.91158349,
        -1.54776799,  0.97024255],
       [ 1.25683526,  0.30659057,  0.91241915, ...,  0.80773656,
         0.64609167, -1.03067011],
       [ 1.46377078, -0.90188624, -1.09598752, ..., -0.91158349,
         0.64609167, -1.03067011]])

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [21]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((7000, 9), (3000, 9), (7000,), (3000,))

In [22]:
from sklearn.naive_bayes import GaussianNB

In [23]:
gnb=GaussianNB()

In [24]:
gnb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [25]:
pred_gnb=gnb.predict(x_test)

In [26]:
pred_gnb

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [28]:
cm=confusion_matrix(y_test,pred_gnb)
cm

array([[2303,   76],
       [ 462,  159]])

In [29]:
score=accuracy_score(y_test,pred_gnb)
score*100

82.06666666666666

In [30]:
from sklearn.model_selection import cross_val_score

In [31]:
cvs=cross_val_score(gnb,x,y,cv=10)
cvs*100

array([83.81618382, 82.11788212, 83.01698302, 81.9       , 82.3       ,
       82.9       , 82.9       , 84.58458458, 82.68268268, 81.68168168])

In [32]:
cvs.mean()*100

82.7899997899998